USE [master]
GO
/****** Object:  Database [GENERALA]    Script Date: 23/11/2023 07:33:27 ******/
CREATE DATABASE [GENERALA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GENERALA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\GENERALA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GENERALA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\GENERALA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [GENERALA] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GENERALA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GENERALA] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GENERALA] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GENERALA] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GENERALA] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GENERALA] SET ARITHABORT OFF 
GO
ALTER DATABASE [GENERALA] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [GENERALA] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GENERALA] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GENERALA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GENERALA] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GENERALA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GENERALA] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GENERALA] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GENERALA] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GENERALA] SET  DISABLE_BROKER 
GO
ALTER DATABASE [GENERALA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GENERALA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GENERALA] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GENERALA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GENERALA] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GENERALA] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GENERALA] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GENERALA] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [GENERALA] SET  MULTI_USER 
GO
ALTER DATABASE [GENERALA] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GENERALA] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GENERALA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GENERALA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GENERALA] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [GENERALA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [GENERALA] SET QUERY_STORE = ON
GO
ALTER DATABASE [GENERALA] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [GENERALA]
GO
/****** Object:  Table [dbo].[Table_Partida]    Script Date: 23/11/2023 07:33:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Table_Partida](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_GANADOR] [int] NOT NULL,
	[PUNTOS] [int] NOT NULL,
 CONSTRAINT [PK_Table_Partida] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Table_Persona]    Script Date: 23/11/2023 07:33:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Table_Persona](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[PASSWORD] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Table_Persona] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Table_Partida] ON 
GO
INSERT [dbo].[Table_Partida] ([ID], [ID_GANADOR], [PUNTOS]) VALUES (1, 1, 999)
GO
INSERT [dbo].[Table_Partida] ([ID], [ID_GANADOR], [PUNTOS]) VALUES (2, 7, 18)
GO
SET IDENTITY_INSERT [dbo].[Table_Partida] OFF
GO
SET IDENTITY_INSERT [dbo].[Table_Persona] ON 
GO
INSERT [dbo].[Table_Persona] ([ID], [NOMBRE], [PASSWORD]) VALUES (1, N'admin', N'admin')
GO
INSERT [dbo].[Table_Persona] ([ID], [NOMBRE], [PASSWORD]) VALUES (4, N'Verstapper', N'1')
GO
INSERT [dbo].[Table_Persona] ([ID], [NOMBRE], [PASSWORD]) VALUES (5, N'Leclerc', N'16')
GO
INSERT [dbo].[Table_Persona] ([ID], [NOMBRE], [PASSWORD]) VALUES (6, N'Hamilton', N'44')
GO
INSERT [dbo].[Table_Persona] ([ID], [NOMBRE], [PASSWORD]) VALUES (7, N'Alonso', N'14')
GO
SET IDENTITY_INSERT [dbo].[Table_Persona] OFF
GO
ALTER TABLE [dbo].[Table_Partida]  WITH CHECK ADD  CONSTRAINT [FK_Table_Partida_Table_Persona] FOREIGN KEY([ID_GANADOR])
REFERENCES [dbo].[Table_Persona] ([ID])
GO
ALTER TABLE [dbo].[Table_Partida] CHECK CONSTRAINT [FK_Table_Partida_Table_Persona]
GO
/****** Object:  StoredProcedure [dbo].[PARTIDA_BORRAR]    Script Date: 23/11/2023 07:33:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create proc [dbo].[PARTIDA_BORRAR]
@id int
as
BEGIN
	delete from Table_Partida where ID = @id
END
GO
/****** Object:  StoredProcedure [dbo].[PARTIDA_INSERTAR]    Script Date: 23/11/2023 07:33:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create proc [dbo].[PARTIDA_INSERTAR]
@idganador int , @puntos int
as
BEGIN
	insert into Table_Partida values (@idganador,@puntos)
END
GO
/****** Object:  StoredProcedure [dbo].[PARTIDA_LISTAR]    Script Date: 23/11/2023 07:33:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create proc [dbo].[PARTIDA_LISTAR]
as
BEGIN
	select * from Table_Partida
END
GO
/****** Object:  StoredProcedure [dbo].[PERSONA_BORRAR]    Script Date: 23/11/2023 07:33:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create proc [dbo].[PERSONA_BORRAR]
@id int
as 
BEGIN
	delete from Table_Persona where ID = @id
END
GO
/****** Object:  StoredProcedure [dbo].[PERSONA_BUSCAR]    Script Date: 23/11/2023 07:33:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create proc [dbo].[PERSONA_BUSCAR]
@nombre varchar(50), @password varchar(50)
as
BEGIN
	select * from Table_Persona where NOMBRE = @nombre and PASSWORD = @password
END
GO
/****** Object:  StoredProcedure [dbo].[PERSONA_EDITAR]    Script Date: 23/11/2023 07:33:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create proc [dbo].[PERSONA_EDITAR]
@nombre varchar(50), @id int
as 
BEGIN
	update Table_Persona set NOMBRE = @nombre where ID = @id
END
GO
/****** Object:  StoredProcedure [dbo].[PERSONA_INSERTAR]    Script Date: 23/11/2023 07:33:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create proc [dbo].[PERSONA_INSERTAR]
@nombre varchar(50), @password varchar(50)
as 
BEGIN
	insert into Table_Persona values (@nombre,@password)
END
GO
/****** Object:  StoredProcedure [dbo].[PERSONA_LISTAR]    Script Date: 23/11/2023 07:33:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create proc [dbo].[PERSONA_LISTAR]
as 
BEGIN
	select * from Table_Persona
END
GO
USE [master]
GO
ALTER DATABASE [GENERALA] SET  READ_WRITE 
GO
